# Welcome to Jekyll!
# https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml


# Site settings
title: Matthiasmunz.de 👋
subtitle: Explore, Learn, Create & Innovate
email: matthias.munz@gmx.de
repository: matmu/matmu.github.io
url: "https://matthiasmunz.de"
baseurl: ""
description: Explore, Learn, Create & Innovate.
twitter_username: _MatthiasMunz
github_username: matmu
minimal_mistakes_skin: default
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-R6WNSZET6Q"


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name   : "Matthias Munz"
  avatar : "/assets/images/portrait_quadr.png"
  bio    : "From a village near Freiburg, Germany. Living and working in Penzberg, Bavaria. Passionate about bioinformatics, climbing and travelling. Adventurer. Programmer. Big data expert. Problem solver. Creator. Autodidact."
  links:
    - label: "Penzberg"
      icon: "fas fa-fw fa-map-marker-alt"
      url: "https://goo.gl/maps/jRkNWky3BkshXo23A"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:matthias.munz@gmx.de"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "http://twitter.com/_MatthiasMunz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "http://github.com/matmu"
    - label: "G. Scholar"
      icon: "ai ai-google-scholar-square adj-academicicons"
      url: "https://scholar.google.de/citations?user=YqZW19IAAAAJ&hl=de"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/matthiasmunz"
    - label: Youtube
      icon: fab fa-fw fa-youtube
      url: "https://www.youtube.com/channel/UC_YAo3WMEkmRzhIEuglf-dA"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/matthias-munz"
    - label: Stackoverflow
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/1150325"
    - label: Orcid
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-4728-3357"
    - label: Docker
      icon: "fab fa-docker"
      url: "http://hub.docker.com/u/matmu"
    - label: Komoot
      icon:
      url: https://www.komoot.com/de-de/user/452401342375
    - label: Geocaching
      icon:
      url: http://www.geocaching.com/profile/?id=20047833
    - label: Warmshowers
      icon:
      url: https://www.warmshowers.org/user/268713


footer:
  links:
#   - label: "Twitter"
#     icon: "fab fa-fw fa-twitter-square"
#     url: "https://twitter.com/"
#   - label: "GitHub"
#     icon: "fab fa-fw fa-github"
#     url: "https://github.com/"
#   - label: "Instagram"
#     icon: "fab fa-fw fa-instagram"
#     url: "https://instagram.com/"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      show_date: true
      date_format: "%B %-d, %Y"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


after_footer_scripts:
  - https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
  - assets/js/clipboardrouge.js
